# Generated by Django 3.2.5 on 2021-07-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quietPlace', '0002_auto_20210714_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='working_hour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='cafe_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pic'),
        ),
    ]
