# Generated by Django 3.2.5 on 2021-07-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quietPlace', '0004_auto_20210715_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='booking_available',
            field=models.TextField(blank=True, null=True),
        ),
    ]
