# Generated by Django 3.2.5 on 2021-07-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quietPlace', '0005_tag_booking_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='franchise',
        ),
    ]
