# Generated by Django 3.2.5 on 2021-07-15 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quietPlace', '0006_remove_tag_franchise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_img', models.ImageField(blank=True, null=True, upload_to='images/cafe_pic')),
                ('cafe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quietPlace.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_img', models.ImageField(blank=True, null=True, upload_to='images/review_pic')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quietPlace.review')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
