# Generated by Django 3.2.5 on 2021-07-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quietPlace', '0007_auto_20210715_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='working_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
