# Generated by Django 3.2.5 on 2021-07-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quietPlace', '0008_cafe_working_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
