# Generated by Django 3.2.5 on 2021-07-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quietPlace', '0010_remove_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
