# Generated by Django 3.2.5 on 2021-07-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='college',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='major',
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='닉네임을 설정해주세요', max_length=20),
        ),
    ]
