# Generated by Django 3.2.5 on 2021-07-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210719_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='post',
            new_name='profile',
        ),
    ]
