# Generated by Django 3.2.5 on 2021-07-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_post_photo_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileimage',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='사용자 프로필사진'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
