# Generated by Django 3.2.5 on 2021-07-23 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_profile_pic'),
        ('accounts', '0007_auto_20210723_1022'),
    ]

    operations = [
    ]
